language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: BUILD_TARGET=trusty_build
    - os: linux
      sudo: required
      services:
        - docker
      env: BUILD_TARGET=docker_build

before_script:
- set -e
- if [[ "${BUILD_TARGET}" = "trusty_build" ]]; then
    sudo wget -O /usr/bin/astyle https://github.com/PX4/astyle/releases/download/2.05.1/astyle-linux;
    sudo chmod +x /usr/bin/astyle;
    sudo apt-get install libcurl4-openssl-dev;
  fi
- if [[ "${BUILD_TARGET}" = "docker_build" ]]; then
    pip install --user awscli; 
    $(aws ecr get-login --region eu-central-1);
    docker pull 879326759580.dkr.ecr.eu-central-1.amazonaws.com/dronelink;
  fi

script:
- if [[ "${BUILD_TARGET}" = "trusty_build" ]]; then
    make;
    make run_unit_tests;
    make fix_style;
  fi
- if [[ "${BUILD_TARGET}" = "docker_build" ]]; then
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw 879326759580.dkr.ecr.eu-central-1.amazonaws.com/dronelink astyle --version
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw 879326759580.dkr.ecr.eu-central-1.amazonaws.com/dronelink make;
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw 879326759580.dkr.ecr.eu-central-1.amazonaws.com/dronelink make run_unit_tests;
    docker run -it -v $TRAVIS_BUILD_DIR:/home/docker1000/src/DroneLink:rw 879326759580.dkr.ecr.eu-central-1.amazonaws.com/dronelink make fix_style;
  fi
